// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzFHkrwQDFBniiVBC6tqacZ9TguvPPAA',
    appId: '1:360272895923:web:78636aae5027776c7875c6',
    messagingSenderId: '360272895923',
    projectId: 'pro-tasker-7a950',
    authDomain: 'pro-tasker-7a950.firebaseapp.com',
    storageBucket: 'pro-tasker-7a950.firebasestorage.app',
    measurementId: 'G-H9VRNGSHQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNFEiDz6Zvot42GtskSUSMGIn0YlMcX4',
    appId: '1:360272895923:android:a2efe6e4ec4a79477875c6',
    messagingSenderId: '360272895923',
    projectId: 'pro-tasker-7a950',
    storageBucket: 'pro-tasker-7a950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSOyAgKv6GJvXl4v0JtwphEuCzIJrjxxM',
    appId: '1:360272895923:ios:2b92efd2d342fa007875c6',
    messagingSenderId: '360272895923',
    projectId: 'pro-tasker-7a950',
    storageBucket: 'pro-tasker-7a950.firebasestorage.app',
    iosClientId: '360272895923-g2f36gpdl7mteqaj7u00iiggf9e5beuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.proTasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSOyAgKv6GJvXl4v0JtwphEuCzIJrjxxM',
    appId: '1:360272895923:ios:2b92efd2d342fa007875c6',
    messagingSenderId: '360272895923',
    projectId: 'pro-tasker-7a950',
    storageBucket: 'pro-tasker-7a950.firebasestorage.app',
    iosClientId: '360272895923-g2f36gpdl7mteqaj7u00iiggf9e5beuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.proTasker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOzFHkrwQDFBniiVBC6tqacZ9TguvPPAA',
    appId: '1:360272895923:web:d28636e23476f65c7875c6',
    messagingSenderId: '360272895923',
    projectId: 'pro-tasker-7a950',
    authDomain: 'pro-tasker-7a950.firebaseapp.com',
    storageBucket: 'pro-tasker-7a950.firebasestorage.app',
    measurementId: 'G-C45GNCJ057',
  );
}
